### ISSUE TITLE
Retina Screen bug in Chrome

### ISSUE THREAD

**Issue by liesju** [MSchmidt/jquery-fullsizable#20]
![schermafbeelding 2016-04-29 om 14 19 11](https://cloud.githubusercontent.com/assets/14106981/14916180/3220b1a2-0e18-11e6-914c-50fc6e7d4ce2.png)

**Comment by MSchmidt** [comment]
Unfortunately I don't have a Retina + Chrome machine available but asked someone who has. He can confirm the issue on your website but cannot reproduce it on this one, which uses this plugin as well: https://www.pt-balance.de

So there must be something special about your page that causes this. Could you evaluate this a little further. Again, since I don't have a capable screen myself I cannot dig any deeper into this issue at the time.
